
serial_row: serial_row.c
	gcc serial_row.c -o serial_row
parallel_row: parallel_row.c
	gcc parallel_row.c -o parallel_row -fopenmp
serial_col: serial_col.c
	gcc serial_col.c -o serial_col
parallel_col: parallel_col.c
	gcc parallel_col.c -o parallel_col -fopenmp
